version: '3.7'

services:
  front_end:
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - CI=true
  back_end:
    build: ./backend
    ports:
      - 8000:8000


# docker-compose up --build -d
# docker-compose down