# Generated by Django 4.1.4 on 2023-07-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.RemoveField(
            model_name="category",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("Information Technology", "Information Technology"),
                    ("Healthcare", "Healthcare"),
                    ("Finance", "Finance"),
                    ("Human Resources", "Human Resources"),
                    ("Media", "Media"),
                ],
                max_length=50,
            ),
        ),
    ]
