# Generated by Django 4.1.4 on 2023-07-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("resume", models.FileField(upload_to="")),
                ("cover_letter", models.TextField()),
                ("application_status", models.BooleanField(default=False)),
            ],
        ),
    ]
