# Generated by Django 4.1.4 on 2023-07-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
