# Generated by Django 4.1.4 on 2023-07-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=50)),
                ("salary", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("experience_required", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("saved", models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
