# Generated by Django 4.1.4 on 2023-07-02 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
        ("jobpost", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="category.category",
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="saved",
            field=models.BooleanField(default=False),
        ),
    ]
