# Generated by Django 4.1.4 on 2023-07-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobpost", "0002_alter_jobpost_category_alter_jobpost_saved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="category",
            field=models.CharField(
                choices=[
                    ("Information Technology", "Information Technology"),
                    ("Healthcare", "Healthcare"),
                    ("Finance", "Finance"),
                    ("Human Resources", "Human Resources"),
                    ("Media", "Media"),
                ],
                max_length=50,
            ),
        ),
    ]
