# Generated by Django 4.1.4 on 2023-07-02 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_remove_category_created_at_and_more"),
        ("jobpost", "0003_alter_jobpost_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="category.category"
            ),
        ),
    ]
