# Generated by Django 4.1.4 on 2023-07-06 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_remove_category_created_at_and_more"),
        ("jobpost", "0006_alter_jobpost_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.category",
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="saved",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
